version: "3.9"
services:
  rest-api:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  database:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "restapi"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"